"""
.. module:: helix

.. moduleauthor:: modlab Alex Mueller <alex.mueller@pharma.ethz.ch>

This module incorporates methods for presumed amphipathic alpha-helical peptide sequences.
These sequences are generated by placing basic residues along the sequence with distance 3-4 AA to each other.
The remaining empty spots are filled up by hydrophobic AAs.
The method :func:`mutate_AA(nr,prob)` enables sequential mutations of the produced sequences.
"""

from core.templates import mutate_AA, aminoacids, template, clean, save_fasta
import random
from itertools import cycle

__author__ = 'modlab'

class Helices:
	'''
	Base class for peptide sequences probable to form helices.
	'''
	def __init__(self,lenmin,lenmax,seqnum):
		'''
		:param lenmin: minimal sequence length
		:param lenmax: maximal sequence length
		:param seqnum: number of sequences to generate
		:return: defined variables as instances
		'''
		aminoacids(self)
		template(self,lenmin,lenmax,seqnum)

	def generate_helices(self):
		'''
		Method to generate amphipathic helical sequences with class features defined in :class:`Helices()`

		:return: In *self.sequences*: a list of sequences with presumed amphipathic helical structure.
		:Example:

		>>> H = Helices(7,21,5)
		>>> H.generate_helices()
		>>> H.sequences
		['KGIKVILKLAKAGVKAVRL','IILKVGKV','IAKAGRAIIK','LKILKVVGKGIRLIVRIIKAL','KAGKLVAKGAKVAAKAIKI']
		'''
		clean(self)
		for s in range(self.seqnum): #for the number of sequences to generate
			seq = ['X'] * random.choice(range(self.lenmin, self.lenmax + 1))
			basepos = random.choice(range(4)) #select spot for first basic residue from 0 to 3
			seq[basepos] = random.choice(self.AA_basic) #place first basic residue
			gap = cycle([3,4]).next #gap cycle of 3 & 4 --> 3,4,3,4,3,4...
			g = gap()
			while g+basepos < len(seq): #place more basic residues 3-4 positions further (changing between distance 3 and 4)
				basepos += g
				seq[basepos] = random.choice(self.AA_basic) #place more basic residues
				g = gap() #next gap

			for p in range(len(seq)):
				while seq[p] == 'X': #fill up remaining spots with hydrophobic AAs
					seq[p] = random.choice(self.AA_hyd)

			self.sequences.append(''.join(seq))


	def mutate_AA(self,nr,prob):
		"""
		Method to mutate with **prob** probability a **nr** of positions per sequence randomly.

		:param nr: number of mutations to perform per sequence
		:param prob: probability of mutating a sequence
		:return: In *self.sequences*: mutated sequences
		:Example:

		>>> H.sequences
		['IAKAGRAIIK']
		>>> H.mutate_AA(3,1)
		>>> H.sequences
		['NAKAGRAWIK']
		"""
		mutate_AA(self,nr,prob)


	def save_fasta(self,filename):
		"""
		Method for saving sequences in the instance self.sequences to a file in FASTA format.

		:param filename: output filename (ending .fasta)
		:return: a FASTA formatted file containing the generated sequences
		"""
		save_fasta(self,filename)